// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PirryLedger.Core.AccessControl.Infrastructure;

#nullable disable

namespace PirryLedger.Core.AccessControl.Infrastructure.Migrations
{
    [DbContext(typeof(AccessControlDbContext))]
    [Migration("20261003142652_UnificarNombresDeColumnas")]
    partial class UnificarNombresDeColumnas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PirryLedger.Core.AccessControl.Domain.CodigoRecuperacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("EmitidoUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("emitido_utc");

                    b.Property<DateTime>("ExpiraUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expira_utc");

                    b.Property<string>("HashDelCodigo")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("hash_del_codigo");

                    b.Property<DateTime?>("UsadoUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("usado_utc");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("HashDelCodigo")
                        .IsUnique()
                        .HasDatabaseName("ix_ac_codigos_recuperacion_hash");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_ac_codigos_recuperacion_usuario");

                    b.ToTable("ac_codigos_recuperacion", (string)null);
                });

            modelBuilder.Entity("PirryLedger.Core.AccessControl.Domain.Sesion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CerradaUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cerrada_utc");

                    b.Property<int>("CredencialVersion")
                        .HasColumnType("integer")
                        .HasColumnName("credencial_version");

                    b.Property<DateTime>("EmitidaUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("emitida_utc");

                    b.Property<DateTime>("ExpiraUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expira_utc");

                    b.Property<string>("HashDelToken")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("hash_del_token");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("ExpiraUtc")
                        .HasDatabaseName("ix_ac_sesiones_expira");

                    b.HasIndex("HashDelToken")
                        .IsUnique()
                        .HasDatabaseName("ix_ac_sesiones_hash");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_ac_sesiones_usuario");

                    b.ToTable("ac_sesiones", (string)null);
                });

            modelBuilder.Entity("PirryLedger.Core.AccessControl.Domain.TokenActivacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("EmitidoUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("emitido_utc");

                    b.Property<DateTime>("ExpiraUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expira_utc");

                    b.Property<string>("HashDelToken")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("hash_del_token");

                    b.Property<DateTime?>("UsadoUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("usado_utc");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("HashDelToken")
                        .IsUnique()
                        .HasDatabaseName("ix_ac_tokens_activacion_hash");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_ac_tokens_activacion_usuario");

                    b.ToTable("ac_tokens_activacion", (string)null);
                });

            modelBuilder.Entity("PirryLedger.Core.AccessControl.Domain.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<DateTime?>("BloqueoHastaUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bloqueo_hasta_utc");

                    b.Property<DateTime?>("ContrasenaCambiadaUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("contrasena_cambiada_utc");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("correo");

                    b.Property<int>("CredencialVersion")
                        .HasColumnType("integer")
                        .HasColumnName("credencial_version");

                    b.Property<DateTime>("FechaDeCreacionUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_de_creacion_utc");

                    b.Property<string>("HashDeContrasena")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("hash_de_contrasena");

                    b.Property<int>("IntentosFallidos")
                        .HasColumnType("integer")
                        .HasColumnName("intentos_fallidos");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("rol");

                    b.HasKey("Id");

                    b.HasIndex("Correo")
                        .IsUnique()
                        .HasDatabaseName("ix_ac_usuarios_correo");

                    b.ToTable("ac_usuarios", (string)null);
                });

            modelBuilder.Entity("PirryLedger.Core.AccessControl.Domain.CodigoRecuperacion", b =>
                {
                    b.HasOne("PirryLedger.Core.AccessControl.Domain.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PirryLedger.Core.AccessControl.Domain.Sesion", b =>
                {
                    b.HasOne("PirryLedger.Core.AccessControl.Domain.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PirryLedger.Core.AccessControl.Domain.TokenActivacion", b =>
                {
                    b.HasOne("PirryLedger.Core.AccessControl.Domain.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
