// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PirryLedger.Core.AccessControl.Infrastructure;

#nullable disable

namespace PirryLedger.Core.AccessControl.Infrastructure.Migrations
{
    [DbContext(typeof(AccessControlDbContext))]
    [Migration("20260930212544_CrearTablasDeControlDeAcceso")]
    partial class CrearTablasDeControlDeAcceso
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PirryLedger.Core.AccessControl.Domain.CodigoRecuperacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EmitidoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiraUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HashDelCodigo")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("UsadoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("HashDelCodigo")
                        .IsUnique()
                        .HasDatabaseName("ix_ac_codigos_recuperacion_hash");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_ac_codigos_recuperacion_usuario");

                    b.ToTable("ac_codigos_recuperacion", (string)null);
                });

            modelBuilder.Entity("PirryLedger.Core.AccessControl.Domain.TokenActivacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EmitidoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiraUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HashDelToken")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("UsadoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("HashDelToken")
                        .IsUnique()
                        .HasDatabaseName("ix_ac_tokens_activacion_hash");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_ac_tokens_activacion_usuario");

                    b.ToTable("ac_tokens_activacion", (string)null);
                });

            modelBuilder.Entity("PirryLedger.Core.AccessControl.Domain.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("BloqueoHastaUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<int>("CredencialVersion")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaDeCreacionUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HashDeContrasena")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("IntentosFallidos")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("Correo")
                        .IsUnique()
                        .HasDatabaseName("ix_ac_usuarios_correo");

                    b.ToTable("ac_usuarios", (string)null);
                });

            modelBuilder.Entity("PirryLedger.Core.AccessControl.Domain.CodigoRecuperacion", b =>
                {
                    b.HasOne("PirryLedger.Core.AccessControl.Domain.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PirryLedger.Core.AccessControl.Domain.TokenActivacion", b =>
                {
                    b.HasOne("PirryLedger.Core.AccessControl.Domain.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
