<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DotNetEnv" Version="3.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
    <PackageReference Include="Microsoft.OpenApi" Version="2.7.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\PirryLedger.Core.Contracts\PirryLedger.Core.Contracts.csproj" />
    <ProjectReference Include="..\..\Core\PirryLedger.Core.AccessControl\PirryLedger.Core.AccessControl.Infrastructure\PirryLedger.Core.AccessControl.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Core\PirryLedger.Core.AccessControl\PirryLedger.Core.AccessControl.Api\PirryLedger.Core.AccessControl.Api.csproj" />
    <ProjectReference Include="..\..\Core\PirryLedger.Core.Notifications\PirryLedger.Core.Notifications.Infrastructure\PirryLedger.Core.Notifications.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Core\PirryLedger.Core.Notifications\PirryLedger.Core.Notifications.Api\PirryLedger.Core.Notifications.Api.csproj" />
    <ProjectReference Include="..\..\Business\PirryLedger.Business\PirryLedger.Business.Application\PirryLedger.Business.Application.csproj" />
    <ProjectReference Include="..\..\Business\PirryLedger.Business\PirryLedger.Business.Domain\PirryLedger.Business.Domain.csproj" />
  </ItemGroup>

</Project>
